### ISSUE TITLE
add new language to conf_schema.json for deepgram STT

### ISSUE THREAD

**Issue by skylinegtr124** [abeiro/HerikaServer#36]
Hi, please add an additional language - Russian - to the file https://github.com/abeiro/HerikaServer/blob/aiagent/conf/conf_schema.json for STT deepgram. It is supported: https://developers.deepgram.com/docs/models-languages-overview. After each server update, I have to manually edit this config. Thank you.

string 241:
"LANG":{"type":"select","values":["en","es","ru"],"description":"Language"},

**Comment by abeiro** [comment]
done
